# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fed_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fed_proto.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x65\x64_proto.proto\x12\x0brpc_package\"n\n\x0eserver_request\x12\x1d\n\x15server_grad_para_data\x18\x01 \x03(\x0c\x12\x1d\n\x15server_grad_para_type\x18\x02 \x03(\t\x12\x1e\n\x16server_grad_para_shape\x18\x03 \x03(\t\"l\n\x0c\x63lient_reply\x12\x1d\n\x15\x63lient_grad_para_data\x18\x01 \x03(\x0c\x12\x1d\n\x15\x63lient_grad_para_type\x18\x02 \x03(\t\x12\x1e\n\x16\x63lient_grad_para_shape\x18\x03 \x03(\t\" \n\x10\x64\x61tasize_request\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1e\n\x0e\x64\x61tasize_reply\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1f\n\x0cstop_request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nstop_reply\x12\x0f\n\x07message\x18\x01 \x01(\t2^\n\x12GradDescentService\x12H\n\x0cgrad_descent\x12\x1b.rpc_package.server_request\x1a\x19.rpc_package.client_reply\"\x00\x32\x62\n\x12GetDataSizeService\x12L\n\x0cget_datasize\x12\x1d.rpc_package.datasize_request\x1a\x1b.rpc_package.datasize_reply\"\x00\x32K\n\x0bstop_server\x12<\n\x04stop\x12\x19.rpc_package.stop_request\x1a\x17.rpc_package.stop_reply\"\x00\x62\x06proto3'
)




_SERVER_REQUEST = _descriptor.Descriptor(
  name='server_request',
  full_name='rpc_package.server_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_grad_para_data', full_name='rpc_package.server_request.server_grad_para_data', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_grad_para_type', full_name='rpc_package.server_request.server_grad_para_type', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_grad_para_shape', full_name='rpc_package.server_request.server_grad_para_shape', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=142,
)


_CLIENT_REPLY = _descriptor.Descriptor(
  name='client_reply',
  full_name='rpc_package.client_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_grad_para_data', full_name='rpc_package.client_reply.client_grad_para_data', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_grad_para_type', full_name='rpc_package.client_reply.client_grad_para_type', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_grad_para_shape', full_name='rpc_package.client_reply.client_grad_para_shape', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=252,
)


_DATASIZE_REQUEST = _descriptor.Descriptor(
  name='datasize_request',
  full_name='rpc_package.datasize_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='rpc_package.datasize_request.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=286,
)


_DATASIZE_REPLY = _descriptor.Descriptor(
  name='datasize_reply',
  full_name='rpc_package.datasize_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='rpc_package.datasize_reply.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=318,
)


_STOP_REQUEST = _descriptor.Descriptor(
  name='stop_request',
  full_name='rpc_package.stop_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.stop_request.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=351,
)


_STOP_REPLY = _descriptor.Descriptor(
  name='stop_reply',
  full_name='rpc_package.stop_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.stop_reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=382,
)

DESCRIPTOR.message_types_by_name['server_request'] = _SERVER_REQUEST
DESCRIPTOR.message_types_by_name['client_reply'] = _CLIENT_REPLY
DESCRIPTOR.message_types_by_name['datasize_request'] = _DATASIZE_REQUEST
DESCRIPTOR.message_types_by_name['datasize_reply'] = _DATASIZE_REPLY
DESCRIPTOR.message_types_by_name['stop_request'] = _STOP_REQUEST
DESCRIPTOR.message_types_by_name['stop_reply'] = _STOP_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

server_request = _reflection.GeneratedProtocolMessageType('server_request', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_REQUEST,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.server_request)
  })
_sym_db.RegisterMessage(server_request)

client_reply = _reflection.GeneratedProtocolMessageType('client_reply', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT_REPLY,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.client_reply)
  })
_sym_db.RegisterMessage(client_reply)

datasize_request = _reflection.GeneratedProtocolMessageType('datasize_request', (_message.Message,), {
  'DESCRIPTOR' : _DATASIZE_REQUEST,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.datasize_request)
  })
_sym_db.RegisterMessage(datasize_request)

datasize_reply = _reflection.GeneratedProtocolMessageType('datasize_reply', (_message.Message,), {
  'DESCRIPTOR' : _DATASIZE_REPLY,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.datasize_reply)
  })
_sym_db.RegisterMessage(datasize_reply)

stop_request = _reflection.GeneratedProtocolMessageType('stop_request', (_message.Message,), {
  'DESCRIPTOR' : _STOP_REQUEST,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.stop_request)
  })
_sym_db.RegisterMessage(stop_request)

stop_reply = _reflection.GeneratedProtocolMessageType('stop_reply', (_message.Message,), {
  'DESCRIPTOR' : _STOP_REPLY,
  '__module__' : 'fed_proto_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.stop_reply)
  })
_sym_db.RegisterMessage(stop_reply)



_GRADDESCENTSERVICE = _descriptor.ServiceDescriptor(
  name='GradDescentService',
  full_name='rpc_package.GradDescentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=384,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='grad_descent',
    full_name='rpc_package.GradDescentService.grad_descent',
    index=0,
    containing_service=None,
    input_type=_SERVER_REQUEST,
    output_type=_CLIENT_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRADDESCENTSERVICE)

DESCRIPTOR.services_by_name['GradDescentService'] = _GRADDESCENTSERVICE


_GETDATASIZESERVICE = _descriptor.ServiceDescriptor(
  name='GetDataSizeService',
  full_name='rpc_package.GetDataSizeService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=480,
  serialized_end=578,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_datasize',
    full_name='rpc_package.GetDataSizeService.get_datasize',
    index=0,
    containing_service=None,
    input_type=_DATASIZE_REQUEST,
    output_type=_DATASIZE_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETDATASIZESERVICE)

DESCRIPTOR.services_by_name['GetDataSizeService'] = _GETDATASIZESERVICE


_STOP_SERVER = _descriptor.ServiceDescriptor(
  name='stop_server',
  full_name='rpc_package.stop_server',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=580,
  serialized_end=655,
  methods=[
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='rpc_package.stop_server.stop',
    index=0,
    containing_service=None,
    input_type=_STOP_REQUEST,
    output_type=_STOP_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOP_SERVER)

DESCRIPTOR.services_by_name['stop_server'] = _STOP_SERVER

# @@protoc_insertion_point(module_scope)
