# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xgb_proto_pb2 as xgb__proto__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xgb_proto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BoosterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_booster = channel.unary_unary(
                '/xgb_package.BoosterService/get_booster',
                request_serializer=xgb__proto__pb2.bst_request.SerializeToString,
                response_deserializer=xgb__proto__pb2.bst_reply.FromString,
                _registered_method=True)


class BoosterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_booster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoosterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_booster': grpc.unary_unary_rpc_method_handler(
                    servicer.get_booster,
                    request_deserializer=xgb__proto__pb2.bst_request.FromString,
                    response_serializer=xgb__proto__pb2.bst_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xgb_package.BoosterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xgb_package.BoosterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BoosterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_booster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xgb_package.BoosterService/get_booster',
            xgb__proto__pb2.bst_request.SerializeToString,
            xgb__proto__pb2.bst_reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stop = channel.unary_unary(
                '/xgb_package.StopService/stop',
                request_serializer=xgb__proto__pb2.stop_request.SerializeToString,
                response_deserializer=xgb__proto__pb2.stop_reply.FromString,
                _registered_method=True)


class StopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stop': grpc.unary_unary_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=xgb__proto__pb2.stop_request.FromString,
                    response_serializer=xgb__proto__pb2.stop_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xgb_package.StopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xgb_package.StopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xgb_package.StopService/stop',
            xgb__proto__pb2.stop_request.SerializeToString,
            xgb__proto__pb2.stop_reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
