# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xgb_proto.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'xgb_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxgb_proto.proto\x12\x0bxgb_package\"\"\n\x0b\x62st_request\x12\x13\n\x0braw_booster\x18\x01 \x01(\x0c\" \n\tbst_reply\x12\x13\n\x0braw_booster\x18\x01 \x01(\x0c\"\x0e\n\x0cstop_request\"\x0c\n\nstop_reply2S\n\x0e\x42oosterService\x12\x41\n\x0bget_booster\x12\x18.xgb_package.bst_request\x1a\x16.xgb_package.bst_reply\"\x00\x32K\n\x0bStopService\x12<\n\x04stop\x12\x19.xgb_package.stop_request\x1a\x17.xgb_package.stop_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xgb_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BST_REQUEST']._serialized_start=32
  _globals['_BST_REQUEST']._serialized_end=66
  _globals['_BST_REPLY']._serialized_start=68
  _globals['_BST_REPLY']._serialized_end=100
  _globals['_STOP_REQUEST']._serialized_start=102
  _globals['_STOP_REQUEST']._serialized_end=116
  _globals['_STOP_REPLY']._serialized_start=118
  _globals['_STOP_REPLY']._serialized_end=130
  _globals['_BOOSTERSERVICE']._serialized_start=132
  _globals['_BOOSTERSERVICE']._serialized_end=215
  _globals['_STOPSERVICE']._serialized_start=217
  _globals['_STOPSERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
